### ISSUE TITLE
TypeError when reading review.json dataset (05_case_study_filter_reviews.ipynb)

### ISSUE THREAD

**Issue by vlbrown** [gtmaskall/dsc_intro#1]
When I first set up the code to read in the review.json dataset, I encountered an error:

`TypeError: sequence item 0: expected str instance, bytes found`

**Code**
```
path 'file://localhost/Users/.../DSC_Intro/'
filename = path + 'yelp_dataset/review_Test.json'
review_reader = pd.read_json(filename, lines=True, chunksize=100000)

for chunk in review_reader:
    print(chunk)
...
```
I changed the code to use 

```
from io import StringIO
...
review_reader = pd.read_json(StringIO(filename), lines=True, chunksize=100000)
```

insead and this error went away. 

Referencing [panda users guide](http://pandas.pydata.org/pandas-docs/stable/user_guide/io.html#line-delimited-json) indicates that the StringIO function is required.

You may want to update the worked notebook accordingly.

**Comment by gtmaskall** [comment]
StringIO() is not appropriate (or correct) here. Future interested readers can find a fuller explanation [in this SO post](https://stackoverflow.com/questions/56727700/valueerror-reading-large-data-set-with-pd-read-json/56820594#56820594)
