### ISSUE TITLE
ValueError when reading review.json dataset (05_case_study_filter_reviews.ipynb)

### ISSUE THREAD

**Issue by vlbrown** [gtmaskall/dsc_intro#2]
After adding `StringIO(...)` to the reader creation code in `05_case_study_filter_reviews.ipynb`. I am encountering a new error when trying to read the review file in chunks.

`ValueError: Unexpected character found when decoding 'false'`

**N.B.** 
* The error only occurs when trying to read the data from a file on disk
    - If the records are placed inline within a string or "here doc" (``` string), the error does not occur
* The error only occurs when trying to read the file in chunks. 
    - If the complete data file is read in, without using chunksize to create a reader, there is no error.
* I have reduced the size of the data set for testing. I can reproduce the error with a single JSON record in the file.

**Sample Data**

Either or both of the following records can be used
```
{"review_id":"rEITo90tpyKmEfNDp3Ou3A","user_id":"6Fz_nus_OG4gar721OKgZA","business_id":"6lj2BJ4tJeu7db5asGHQ4w","stars":5.0,"useful":0,"funny":0,"cool":0,"text":"We've been a huge Slim's fan since they opened one up in Texas about two years ago when we used to live there. This place never disappoints. They even have great salads and grilled chicken. Plus they have fresh brewed sweet tea, it's the best!","date":"2017-05-26 01:23:19"}
{"review_id":"Amo5gZBvCuPc_tZNpHwtsA","user_id":"DzZ7piLBF-WsJxqosfJgtA","business_id":"qx6WhZ42eDKmBchZDax4dQ","stars":5.0,"useful":1,"funny":0,"cool":0,"text":"Our family LOVES the food here. Quick, friendly, delicious, and a great restaurant to take kids to. 5 stars!","date":"2017-03-27 01:14:37"}
```

**Error Output**
![Screen Shot 2019-06-23 at 19 27 42](https://user-images.githubusercontent.com/703084/60304126-53ac9080-98ed-11e9-8dc7-d4e43947ac0d.png)

I have filed [an issue with pandas-dev](https://github.com/pandas-dev/pandas/issues/27022)  as well as a [question on stackexchange](https://stackoverflow.com/questions/56727700/valueerror-reading-large-data-set-with-pd-read-json), but haven't gotten very far.

**Comment by gtmaskall** [comment]
The StringIO() "solution" is a red herring here. The most interesting question, to my mind, to pose to the pandas developers is the different behaviour in pd.read_json(file_buff, ..., chunksize=n) depending on whether file_buff is a file URL or an OS path.

**Comment by vlbrown** [comment]
Yep. I left out the StringIO part for the pandas team. That's only for you because it seems to be required to get past the first error..

I do not believe that the ValueError is being caused by anything in your (or my) code.

> On Jun 29, 2019, at 13:20 , Guy Maskall <notifications@github.com> wrote:
> 
> The StringIO() "solution" is a red herring here. The most interesting question, to my mind, to pose to the pandas developers is the different behaviour in pd.read_json(file_buff, ..., chunksize=n) depending on whether file_buff is a file URL or an OS path.
> 

-- Vicki

Vicki Brown
cfcl.com/vlb
